name: Newman Test Run
on:
  push:
    branches:
    - master
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          collectionID: 10954437-8cb0d465-dff6-4319-a607-caad24998335
          environmentID: 98798-a974f882-8ecg0-4c80-9901-a583778393987a
      - run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra
      - run: newman run HerRide.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > runreport1.html
